name: Build Easy-budget for Windows

on:  [push, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR:  build_wine

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # access issues during checkout: set root user 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mja-71/wine_qt_dev:0.1
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      # Build your program with the given configuration
      run: |
        su - wine -c "wine64  /__w/easy_budget/easy_budget/scripts/build_wine.bat"
      # cd scripts
      # ./build_wine.bat
      
    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: EasyBudget_1.0-win64.exe 
        path: ${{env.BUILD_DIR}}/EasyBudget_1.0-win64.exe
    